Repository Newbiesiuuuu/Backend, pull requests merged in 2023-10, with the labels that each got.

#50 "🐛 fix : 게시글 검색 로직 수정 및 변경"
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/PostController.php
  app/Models/Comment.php
  app/Models/Post.php
  app/Models/User.php
  app/Models/like.php
  routes/api.php
Labels: ✨ Feature, 🐞 BugFix

#52 ✨ feat : 댓글 좋아요 기능 구현 및 댓글 라우트주소 변경
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/PostController.php
  app/Models/Like.php
  routes/api.php
Labels: 🔨 Refactor, ✨ Feature

#53 ✨ feat : Create migration file
  database/migrations/2023_10_06_151459_add_like_count_column_on_comments_table.php
Labels: ✨ Feature

#54 🐛 fix : 게시글 조회시 response에 댓글 작성자 데이터 포함 시키도록 수정
  app/Http/Controllers/PostController.php
  app/Models/Comment.php
  app/Models/User.php
Labels: 🐞 BugFix

#55 ✅ test : Update README.md
  README.md
Labels: ✅ Test

#56 ✨ feat : 게시글 조회시 response 에 liked 추가...
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/PostController.php
  app/Models/Comment.php
  app/Models/Like.php
  app/Models/User.php
Labels: ✨ Feature, 🐞 BugFix

#57 🐛 fix : modified comments_unlike logic
  app/Http/Controllers/CommentController.php
Labels: 🐞 BugFix

#58 🐛 fix : 제목+내용 검색 로직 수정
  app/Http/Controllers/PostController.php
Labels: 🐞 BugFix
